### ISSUE TITLE
AttributeError: 'module' object has no attribute 'IndentCommand'

### ISSUE THREAD

**Issue by boundless08** [socsieng/IndentX#9]
The module just stopped working, nothing else was installed to sublime and nothing edited. Output from console is below:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 115, in create_text_commands
  File ".\IndentX.py", line 23, in __init__
    self.command = commands.IndentCommand(self.view, sublime)
AttributeError: 'module' object has no attribute 'IndentCommand'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 115, in create_text_commands
  File ".\IndentX.py", line 23, in __init__
    self.command = commands.IndentCommand(self.view, sublime)
AttributeError: 'module' object has no attribute 'IndentCommand'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 115, in create_text_commands
  File ".\IndentX.py", line 23, in __init__
    self.command = commands.IndentCommand(self.view, sublime)
AttributeError: 'module' object has no attribute 'IndentCommand'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 115, in create_text_commands
  File ".\IndentX.py", line 23, in __init__
    self.command = commands.IndentCommand(self.view, sublime)
AttributeError: 'module' object has no attribute 'IndentCommand'

Thanks in advance for any help!

**Comment by socsieng** [comment]
Thanks for the feedback. I suspect that it is related to issue #7. I expect to fix this in the next few hours. In the mean time, the work-around is to restart Sublime. Let me know if restarting doesn't resolve your issue.

**Comment by boundless08** [comment]
Thanks for the quick reply, unfortunately restarting sublime doesn't have any effect. Same output in console.

I even tried uninstalling the package and reinstalling but still have the same issue

**Comment by socsieng** [comment]
Can you tell me which version is installed?

**Comment by socsieng** [comment]
I've updated the package to v0.7.5. Can you let me know if upgrading to this package fixes your issue?

**Comment by boundless08** [comment]
Package Control: Upgraded IndentX to v0.7.5

Once package updated it started working again. thanks very much, I hadn't realised how much I relied on this plugin for work!

**Comment by socsieng** [comment]
Thanks, I appreciate the feedback. Just out of interest what are you using it for primarily? JSON or XML?

**Comment by boundless08** [comment]
Just XML. Plugin is a lifesaver though. Request/response from our app logs are all on the same line so just a massive block of unreadable text
